# بخش ششم:رشته‌ها


## محاسبه طول متن


['len']{dir=ltr}
 یک تابع داخلی در پایتون است که تعداد کاراکترهای یک رشته را برمی‌گرداند.


```{python}
fruit = 'banana'
length = len(fruit)
```

حال اگر این عدد را به عنوان اندیس متغیر رشته استفاده کنیم، آخرین کاراکتر رشته را 
بدست می‌آوریم:

```{python}
last = fruit[length - 1]
print(last)
```

دلیل این تفریق این است که شماره اندیس اولین کاراکتر رشته، با صفر شروع می‌شود.

بنابراین برای دستیابی به موقعیت‌های دیگر یک رشته، می‌توان اندیس‌ها را تغییر داد:


```{python}
fruit = 'banana'
fruit[:3]
```


## رشته‌ها تغییرناپذیرند

درعین حال اینکه می‌توان به همه کاراکترهای یک رشته دست پیدا کرد، اما نمی‌توان 
کاراکتر دیگری را جایگزین یکی از کاراکترهای رشته کرد:


```{python}
greeting = 'Hello, world!'
greeting[0] = 'J'
```

اگر این دستور را اجرا کنید، با خطا مواجه می‌شوید، چراکه رشته‌ها قابل تغییر 
نیستند.

## عملگر 
['in']{dir=ltr}

گاربرد این عملگر زمانی است که می‌خواهیم بدانیم آیا یک رشته حاوی یک رشته و یا کاراکتر خاصی هست یا خیر:

```{python}
'a' in 'banana'
```

و یا این حالت:


```{python}
'seed' in 'banana'
```


همچنین با استفاده از عملگرهای 
['<']{dir=ltr}
 و 
['>']{dir=ltr}
 می‌توانیم رشته‌ها را از نظر ترتیب حروف الفبا با یکدیگر مقایسه کنیم:
 
 
```{python}
if word < 'banana':
  print('Your word,' + word + ', comes before banana.')
elif word > 'banana':
  print('Your word,' + word + ', comes after banana.')
else:
  print('All right, bananas.')
```

## متدهای رشته‌ای^[
['String methods']{dir=ltr}
]


پایتون تابعی به نام 
['dir']{dir=ltr} 
دارد که متدهای مربوط به یک شیئ را لیست می‌کند و همچنین با استفاده از 
['type']{dir=ltr}
 می‌توانیم نوع شیئ را تشخیص دهیم: 

```{python}
stuff = 'Hello world'
type(stuff)
```

و


```{python}
dir(stuff)
```

روش دیگر برای یافتن موقعیت یک زیررشته و یا یک کاراکتر خاص در یک رشته اصلی، 
استفاده از متد 
['find']{dir-ltr}
 می‌باشد:
 
 
```{python}
word = 'banana'
index = word.find('a')
print(index)
```
 
 
 خوب است با متدهای 
 ['strip']{dir=ltr}
 
 و
 
  ['startwith']{dir=ltr}

 و
 
  ['lower']{dir=ltr}

 برای آشنایی بیشتر با متدهای رشته‌ای، در برنامه پایتون خودمان تمرین کنیم.
 
 
 ## عملگر فرمت^[
 ['Format operator']{dir=ltr}
 ]
 
 
 عملگر 
 
['format']{dir=ltr}

، % به ما اجازه می‌دهد تا رشته‌ها را بسازیم و بخش‌هایی از رشته‌ها را با داده‌های 
ذخیره شده در متغیرها جایگزین کنیم: 


```{python}
camels = 42
'%d' % camels
```

در مثال بالا توانستیم  حروف 4 و 2 را به عدد 42 تبدیل کنیم.

['d']{dir=ltr}

 مخفف "اعشاری" است.
 
 
 و یا این مثال:
 
 
```{python}
camels = 42
'I have spotted %d camels.' % camels
```

به همین ترتیب، عملگرهای 

['%g']{dir=ltr}
 
 و
 
['%s']{dir=ltr}

 وظیفه قالب‌بندی یک عدد ممیز شناور و قالب‌بندی یک رشته را به عهده دارند:
 
 
```{python}
'In %d years I have spotted %g %s.' % (3, 0.1, 'camels')
```
