#بخش دوم:  متغیرها، عبارات و دستورات
‌

## مقادیر و انواع


مقدار یا 
**Value** 
اصلی‌ترین چیزی است که یک برنامه با آن کار می‌کند و می‌تواند محتوای عددی و یا حرفی
داشته باشد.
اگر نمی‌دانید نوع یک مقدار (عددی یا حرفی) چیست، با دستور زیر می‌توانید از 
مفسر پایتون بخواهید آن را برای شما نشان دهد.


```
> type('Hello, World!')
<class 'str'>

> type(17)
<class 'int'>

> type(3.2)
<class 'float'>

type('17')
<class 'str'>
```

## متغیرها

یکی از قدرتمندترین ویژگی‌های یک زبان برنامه‌نویسی، توانایی دستکاری متغیرها یا همان 
Variables 
است. یک متغیر، نامی است که به یک مقدار اشاره دارد.

یک دستور انتساب متغیرهای جدیدی را ایجاد می‌کند و به آنها مقادیری منتسب می‌کند.

```
> message = 'And now for something completely different'
> n = 17
> pi = 3.1415926535897931
```

در اینجا علامت تساوی (=)، به مفهوم عملگر انتساب است و نه مساوی بودن 
عبارت‌های چپ و راست علامت تساوی!

نوع یک متغیر، نوع مقداری است که به آن اشاره دارد:

```
> type(message)
<class 'str'>
> type(n)
<class 'int'>
> type(pi)
<class 'float'>
```

## دستورات

دستور یک واحد کد است که مفسر پایتون می‌تواند آن را اجرا کند.
مثلاً دستورات چاپ 
(print) 
و انتساب، هرکدام یک دستور محسوب می‌شوند.

یک اسکریپت معمولاً شامل دنباله‌ای از دستورات است. اگر بیش از یک دستور وجود داشته
باشد، نتایج در یک زمان با اجرای دستورات ظاهر می‌شوند.

## عملگرها و عملوندها

**عملگرها 
(Operators )** 
نمادهای خاصی هستند که محاسباتی مانند جمع و ضرب را نشان می‌دهند. مقادیری که عملگر 
روی آنها اعمال می‌شود **عملوند
(Operands )**
 نامیده می‌شوند.
 
 ## عبارات
 
 عبارت ترکیبی از مقادیر، متغیرها و عملگرها است.
 
 یک مقدار به خودی خود یک عبارت در نظر گرفته می‌شود، و همچنین یک متغیر.
 بنابراین موارد زیر همه عبارات قانونی هستند (با فرض اینکه به متغیر
 x 
یک مقدار اختصاص داده شده است):

```
17
x
x + 17
```

## ترتیب عملیات

هنگامی که بیش از یک عملگر در یک عبارت ظاهر می‌شود، ترتیب ارزیابی به قوانین تقدم 
بستگی دارد. برای عملگرهای ریاضی، پایتون از قراردادهای ریاضی پیروی می‌کند.

مخفف 
PEMDAS 
یک روش مفید برای به خاطر سپردن قوانین است:

1- Parentheses

2- Exponentiation

3- Multiplication and Division

4- Addition and Subtraction

اپراتورهایی با اولویت یکسان از چپ به راست ارزیابی می‌شوند. 
بنابراین عبارت 5-3-1 برابر با1 است نه 3، زیرا ابتدا 5-3 اتفاق می‌افتد 
و سپس 1 از 2 کم می‌شود.

## عملگر ماژول 
(Modulus)

عملگر ماژول روی اعداد صحیح کار می‌کند و 
با تقسیم عملوند اول بر دومی، باقیمانده را به دست می‌دهد. 
در پایتون، عملگر ماژول یک علامت درصد 
(%) 
است. 
نحو (نوشتار) آن، مانند سایر عملگرهاست:

```
> quotient = 7 // 3
> print(quotient)
2

> remainder = 7 % 3
> print(remainder)
1
```

## عملگرهای رشته‌ای

عملگر + با رشته ها کار می‌کند، اما به معنای ریاضی جمع نیست.
درواقع استفاده از آن به همراه رشته، به معنی الحاق رشته‌ها به همدیگر است. مثلاً: 

```
> first = 10
> second = 15
> print(first+second)
25

> first = '100'
> second = '150'
> print(first + second)
100150
```

عملگر * همچنین با ضرب محتوای یک رشته در یک عدد صحیح با رشته ها کار می‌کند.
 مثلاً:
 
 ```
> first = 'Test '
> second = 3
> print(first * second)
Test Test Test
 ```
 
 ## درخواست ورودی از کاربر
 
 پایتون یک تابع داخلی به نام ورودی 
(Input)
ارائه می‌کند که ورودی را از صفحه کلید دریافت می‌کند.

```
> name = input('What is your name?\n')
What is your name?
Chuck

> print(name)
Chuck
```

## توضیحات

همانطور که برنامه‌ها بزرگتر و پیچیده‌تر می‌شوند، خواندن آنها دشوارتر می‌شود.
ایده خوبی است که یادداشت‌هایی را به برنامه‌های خودمان اضافه کنیم 
تا به زبان طبیعی توضیح دهیم که برنامه ما چه کاری انجام می‌دهد.
این یادداشت ها **توضیح 
(Comment)** 
نامیده می‌شوند و در پایتون با علامت # شروع می‌شوند:

```
# compute the percentage of the hour that has elapsed
percentage = (minute * 100) / 60
```

## اشکال زدایی

در این مرحله، خطای نحوی که به احتمال زیاد مرتکب آن می‌شویم، 
یک نام متغیر غیرقانونی است، مانند 
class 
و 
yield 
که کلمات کلیدی هستند، یا 
odd~job 
و 
US$ 
که حاوی کاراکترهای غیرقانونی هستند.

```
> bad name = 5
SyntaxError: invalid syntax
> month = 09
File "<stdin>", line 1
month = 09
^
SyntaxError: invalid token
```

