# توابع {#functions}

## فراخوانی تابع {#import-function}

در حوزه برنامه‌نویسی،
یک تابع دنباله‌ای از جملات است که یک محاسبات را انجام می‌دهد.
درواقع ما با تعیین یک نام و یک سری دستورات،
می‌توانیم یک تابع را تعریف کنیم و آنگاه با صداکردن نام آن تابع،
خواهیم توانست آن را فراخوانی کنیم. بسیاری از دستوراتی را که
 تابحال از آن‌ها استفاده می‌کردیم، درواقع تابع بودند:

```python
type(32)
```
```output
<class 'int'>
```


که در این جا نام تابع 
[`type`]{dir=ltr}
است.

## توابع داخلی {#built-in-functions}

توابع داخلی 
[(Built-in)]{dir=ltr}
این‌ها توابعی هستند که توسط سازندگان پایتون تعبیه شده‌اند
 و برای حل مسائل عمومی مورد استفاده قرار می‌گیرند.

نمونه‌ای از این توابع عبارتند از:

```python
max('Hello world')
```
```output
'w'
```

```python
min('Hello world')
```
```output
' '
```

```python
len('Hello world')
```
```output
11
```

## توابع تبدیل نوع {#type-conversion-functions}

توابع تبدیل نوع 
[(Type Conversion)]{dir=ltr}
این‌ها نوع دیگری از توابع داخلی هستند که مقدار یک نوع را
به نوعی دیگر تبدیل می‌کنند:

```python
int(3.99999)
```
```output
3
```

```python
int(-2.3)
```
```output
-3
```

```python
float('3.14159')
```
```output
3.14159
```

## توابع ریاضی {#math-functions}

پایتون دارای یک ماژول ریاضی است که اکثر توابع ریاضی 
مشهور را ارائه می‌دهد. اما قبل از اینکه بتوانیم از ماژول
استفاده کنیم، باید آن را وارد
[(`import`)]{dir=ltr}
کنیم:

```python
import math
```

این عبارت یک شی ماژول به نام
[`math`]{dir=ltr} 
ایجاد می کند.

برای دسترسی به یکی از توابع، باید نام ماژول و
نام تابع را که با یک نقطه از هم جدا شده اند 
(که به عنوان نقطه نیز شناخته می شود) مشخص کنیم.
به این فرمت، علامت نقطه می گویند.

```python
ratio = signal_power / noise_power
decibels = 10 * math.log10(ratio)
radians = 0.7
height = math.sin(radians)
```

## اعداد تصادفی {#random-numbers}

به نظر می‌رسد که ساختن یک برنامه واقعاً غیر قطعی
چندان آسان نیست، اما راه‌هایی وجود دارد که حداقل 
غیرقطعی به نظر برسد. یکی از آنها استفاده از 
الگوریتم‌هایی است که اعداد شبه تصادفی
[(Random)]{dir=ltr}
تولید می‌کنند. 
درست است که اعداد شبه تصادفی واقعاْ تصادفی نیستند 
اما بازهم تمایز آن‌ها از اعداد تصادفیُ غیرممکن است. 

ماژول
[`random`]{dir=ltr} 
توابعی را بدست می‌دهد که اعداد تصادفی تولید می‌کنند.

یک مثال را باهم ببینیم:

```python
import random

for i in range(10):
    x = random.random()
    print(x)

```
```output
0.0920530236235576
0.6250171315179012
0.7706549349232131
0.7402147110407385
0.15988207593735793
0.4024047009691475
0.8179640452074257
0.44502244153994786
0.8980030614870437
0.9357510761663985
```

این برنامه یک لیستی از اعداد تصادفی بین 
`0`
و 
`1`
تولید می‌کند که شامل 
`1`
نمی‌شوند:


مثال‌هایی دیگر از توابع
[`random‌`]{dir=ltr}
عبارتند از: 

```python
random.randint(5, 10)
```
```output
7
```

```python
t = [1, 2, 3]
random.choice(t)
```
```output
3
```

## افزودن یک تابع جدید {#create-new-function}

ما معمولاْ برای پیشبرد اهداف برنامه موردنظرمان،
نیاز به تعریف توابع جدید خواهیم داشت. این توابع
در آینده بارها و بارها می‌توانند مورد استفاده قرار گیرند.

در مثال زیر، یک تابع به نام 
[`print_lyrics`]{dir=ltr}
تعریف می‌کنیم:

```python
def print_lyrics():
    print("I'm a lumberjack, and I'm okay.")
    print('I sleep all night and I work all day.')

```

همانطور که در این مثال می‌بینید، کلمه کلیدی 
[`def`]{dir=ltr}
برای تعریف تابع بکار برده می‌شود. 
با تعریف یک تابع، یک متغیر با همان نام ایجاد می‌شود. 
نحو فراخوانی تابع جدید مانند توابع داخلی است:

```python
print_lyrics()
```
```output
I'm a lumberjack, and I'm okay.
I sleep all night and I work all day.
```

ما حتی می‌توانیم یک تابع تعریف شده را درون تابع دیگر، 
فراخوانی کنیم.

## پارامترها و آرگومان‌ها {#parameters-and-arguments}

برخی از توابع داخلی که دیده‌ایم به آرگومان نیاز دارند. 
برای مثال، وقتی تابع 
[`math.sin`]{dir=ltr}
را فراخوانی می‌کنیم، باید یک عدد را به آن بدهیم.
به این ورودی، آرگومان
[(Argument)]{dir=ltr}

گفته می‌شود.

## توابع دارای خروجی و توابع بدون خروجی {#fruitful-functions-and-void-functions}

در اجرای برخی توابع، با اتمام آخرین دستور تابع،
مقداری را به عنوان نتیجه
 در خروجی می‌بینیم.
این توابع را
[Fruitful]{dir=ltr}
می‌نامند:

```python
import math

math.sqrt(5)
```
```
2.23606797749979
```


اما این اتفاق برای همه توابع رخ نمی‌دهد.
درواقع این توابع کاری را انجام 
داده‌اند که بصورت خروجی قابل نمایش نیست. 
این توابع را 
[Void]{dir=ltr}
می‌نامند:

```python
def No_reult_func ():
    x = math.cos(radians)

```
