# لیست‌ها {#lists}

## لیست یک دنباله است {#a-list-is-a-sequence}

برای کنارهم قرار دادن چندین داده با نوع مختلف، می‌توان از لیست استفاده کرد. 
یکی از راه‌های ایجاد لیست، بکاربردن براکت در تعریف آن است:


```python
cheeses = ['Cheddar', 'Edam', 'Gouda']
numbers = [17, 123]
empty = []
print(cheeses, numbers, empty)
```
```output
['Cheddar', 'Edam', 'Gouda'] [17, 123] []
```

اما همانطور که گفته بودیم، عناصر لیست می‌توانند نوع‌های متفاوت از هم داشته باشند:


```python
multi_types_items = ['spam', 2.0, 5, [10, 20]]
```

در دو مثال قبلی؛ تعداد عناصر لیست را به این شکل محاسبه می‌کنیم:

لیست 
[`cheeses`]{dir=ltr} 
دارای 3 عنصر است. 
لیست 
[`numbers`]{dir=ltr} 
دو عنصر دارد و لیست 
[`multi_types_items`]{dir=ltr} 
شامل 4 عنصر می‌شود. چراکه لیست داخلی که شامل عناصر 10 و 20 هست، در لیست اصلی، 
به عنوان یک عنصر و یا داده درنظرگرفته می‌شود. 

برای تغییر مقادیر موجود در لیست، می‌بایست بتوانیم به هر داده دسترسی داشته باشیم، 
به این منظور از اندیس برای آدرس‌دهی استفاده می‌کنیم:


```python
numbers = [17, 123]
numbers[1] = 5
print(numbers)
```
```output
[17, 5]
```

و یا برای اینکه بدانیم داده مورد نظر ما در لیست قرار گرفته یا خیر، می‌توان از 
این روش استفاده کرد:


```python
cheeses = ['Cheddar', 'Edam', 'Gouda']
'Edam' in cheeses
```
```output
True
```

و یا:
 
 
```python
cheeses = ['Cheddar', 'Edam', 'Gouda']
'Brie' in cheeses
```
```output
False
```


## پیمایش در لیست {#traversing-a-list}

مواقعی هست که می‌خواهیم کل یک لیست را پیمایش کنیم و داده‌های آن را در یک عملیات 
محاسبه‌ای و یا هرنوع عملیات دیگر، وارد سازیم، در اینصورت:


```python
for cheese in cheeses:
    print(cheese)
```
```output
Cheddar
Edam
Gouda
```

این کار بسیار ساده بود. چرا که ما تمام لیست را یکی یکی پیمایش کردیم و آن را در 
خروجی چاپ کردیم. اما اگر نیاز داشته باشیم که در حین پیمایش، داده‌ای از لیست را
تغییر دهیم، چه روشی را باید درپیش بگیریم؟

```python
for i in range(len(numbers)):
    numbers[i] = numbers[i] * 2
```

## کارکردن با عناصر لیست {#work-with-list-items}

در قطعه کد زیر، به ترتیب با استفاده از عملگرهای 
[`+`]{dir=ltr} 
و 
[`*`]{dir=ltr} 
آشنا می‌شویم و سپس نحوه برش‌های مختلف لیست را یادمی‌گیریم:


```python
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(c)
```
```output
[1, 2, 3, 4, 5, 6]
```


```python
[1, 2, 3] * 3
```
```output
[1, 2, 3, 1, 2, 3, 1, 2, 3]
```


```python
t = ['a', 'b', 'c', 'd', 'e', 'f']
t[1:3]
```
```
['b', 'c']
```

```python
t[:4]
```
```
['a', 'b', 'c', 'd']
```

```python
t[3:]
```
```
['d', 'e', 'f']
```

## متدهای لیست {#list-methods}

برای اضافه کردن یک عنصر به انتهای لیست، می‌توانیم از متد 
[`append()`]{dir=ltr} 
استفاده کنیم:

```python
t = ['a', 'b', 'c']
t.append('d')
print(t)
```
```output
['a', 'b', 'c', 'd']
```

همچنین متد 
[`extend()`]{dir=ltr} 
یک لیست را به عنوان آرگومان ورودی دریافت می‌کند و آن را به انتهای لیست معرفی شده، 
اضافه می‌کند:

```python
t1 = ['a', 'b', 'c']
t2 = ['d', 'e']
t1.extend(t2)
print(t1)
```
```
['a', 'b', 'c', 'd', 'e']
```

برای مرتب کردن عناصر یک لیست، متد 
[`sort()`]{dir=ltr} 
در اختیار ماست: 

```python
t = ['d', 'c', 'e', 'b', 'a']
t.sort()
print(t)
```
```output
['a', 'b', 'c', 'd', 'e']
```

اگر چنانچه خواسته باشیم عنصری را از داخل یک لیست حذف کنیم، با دانستن اندیس موقعیت 
آن عنصر، می‌توانیم از متد 
['pop(i)']{dir=ltr} 
استفاده کنیم: 

```python
t = ['a', 'b', 'c']
x = t.pop(1)
print(t)
```
```output
['a', 'c']
```


```python
print(x)
```
```
b
```

اگر در استفاده از دستور 
[`pop()`]{dir=ltr} 
اندیس استفاده نشود، این متد، آخرین عنصر آرایه را حذف خواهد کرد. 

به کد زیر و نتیجه اجرای آن دقت کنید: 

```python
t = ['a', 'b', 'c']
del t[1]
print(t)
```
```
['a', 'c']
```


به نظر شما تفاوت استفاده از متدهای 
[`pop(i)`]{dir=ltr} 
و 
[`del list_name[i]`]{dir=ltr} 
در چیست؟ 

بله، درست است که هر دو باعث حذف یک عنصر از لیست می‌شوند اما در استفاده از متد 
[`pop(i)`]{dir=ltr} 
عنصر حذف شده در اختیار ما خواهد بود. به این معنی که خروجی این متد، نمایانگر 
مقدار عنصر حذف شده است. اما در استفاده از دستور 
[`del list_name[i]`]{dir=ltr} 
عنصری که حذف شده دیگر در دسترس ما نخواهد بود. 

حال به این سوال فکر کنید که اگر اندیس عنصر موردنظر برای حذف کردن را ندانیم، 
از چه روشی می‌توانیم آن عنصر خاص را حذف کنیم؟ 
درواقع پایتون برای این منظور متد 
[`remove(item_value)`]{dir=ltr} 
را پیشنهاد می‌دهد که با ارسال مقدار عنصر موردنظر به عنوان آرگومان ورودی به این 
متد، می‌توانیم آن را از لیست حذف کنیم: 


```python
t = ['a', 'b', 'c']
t.remove('b')
print(t)
```
```output
['a', 'c']
```

و یا برای حذف بیش از یک مقدار، با دانستن اندیس آن‌ها می‌توان از روش زیر استفاده 
کرد: 

```python
t = ['a', 'b', 'c', 'd', 'e', 'f']
del t[1:5]
print(t)
```
```output
['a', 'f']
```


## برخی توابع مهم مربوط به لیست {#important-function-for-lists}


در کدهای زیر نام و کاربرد برخی توابع مهم برای استفاده در لیست‌ها معرفی شده‌اند: 

```python
nums = [3, 41, 12, 9, 74, 15]
print(len(nums))
```
```output
6
```


```python
print(max(nums))
```
```output
74
```

```python
print(min(nums))
```
```output
3
```


```python
print(sum(nums))
```
```output
154
```

```python
print(sum(nums)/len(nums))
```
```output
25.666666666666668
```

## لیست‌ها و رشته‌ها {#lists-strings}


یک رشته، دنباله‌ای از کاراکترهاست و یک لیست دنباله‌ای از عناصر. 
اما یک لیست از کاراکترها، همانند یک رشته نیست. برای تبدیل یک رشته به یک لیست، 
می‌توان از متد یا تابع 
[`list(string_name)`]{dir=ltr} 
استفاده کرد:

```python
s = 'spam'
t = list(s)
print(t)
```
```output
['s', 'p', 'a', 'm']
```

اما اگر بخواهیم رشته‌ای از کلمات را به لیست تبدیل کنیم، چه باید کرد:


```python
s = 'pining for the fjords'
t = s.split()
print(t)
```
```output
['pining', 'for', 'the', 'fjords']
```

و یا مثالی دیگر که در آن با کاربرد توابع 
[`split(delimiter)`]{dir=ltr} و
[`join(list_name)`]{dir=ltr} 
آشنا می‌شویم:


```python
s = 'spam-spam-spam'
delimiter = '-'
s.split(delimiter)
```
```output
['spam', 'spam', 'spam']
```

```python
t = ['pining', 'for', 'the', 'fjords']
delimiter = ' '
delimiter.join(t)
```
```output
'pining for the fjords'
```